classification:
  - accuracy
  - precision
  - recall
  - f1
  - f1_macro
  - f1_weighted
  - roc_auc
  - log_loss
  - kappa
  - mcc

regression:
  - mae
  - mse
  - rmse
  - r2
  - mape
  - max_error
